insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Látvia', 'LVA', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Lesoto', 'LSO', 'Lesoto', 266, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Líbano', 'LBN', 'Libanesa', 961, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Libéria', 'LBR', 'Liberiano', 231, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Líbia', 'LBY', 'Líbio', 218, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Liechtenstein', 'LIE', 'Liechtensteiniense', 423, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Lituânia', 'LTU', 'Lituano', 370, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Luxemburgo', 'LUX', 'Luxemburguês', 352, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Macau', 'MAC', '', 853, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Macedônia', 'MKD', 'Macedônio', 389, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Madagascar', 'MDG', 'Malgache', 261, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Malásia', 'MYS', 'Malaio', 60, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Malaui', 'MWI', 'Malauiano', 265, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Maldivas', 'MDV', '', 960, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Mali', 'MLI', 'Malinês', 223, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Malta', 'MLT', 'Maltês', 356, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Marrocos', 'MAR', 'Marroquina', 212, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Martinica', 'MTQ', 'Martinicano', 596, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Maurício', 'MUS', 'Mauriciano', 230, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Mauritânia', 'MRT', 'Mauritano', 222, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Mayotte', 'MYT', 'Maiotense', 269, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('México', 'MEX', 'Mexicana', 52, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Micronésia', 'FSM', 'Micronésio', 691, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Moçambique', 'MOZ', 'Moçambicano', 258, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Moldova', 'MDA', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Mônaco', 'MCO', 'Monegasco', 377, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Mongólia', 'MNG', 'Mongol', 976, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Montserrat', 'MSR', '', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Myanmar', 'MMR', '', 95, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Namíbia', 'NAM', 'Namibiano', 264, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Nauru', 'NRU', 'Nauruano', 674, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Nepal', 'NPL', 'Nepalês', 977, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Nicarágua', 'NIC', 'Nicaragüense', 505, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Níger', 'NER', 'Nigerense', 227, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Nigéria', 'NGA', 'Nigeriana', 234, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Niue', 'NIU', 'Niuense', 683, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Noruega', 'NOR', 'Norueguesa', 47, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Nova Caledônia', 'NCL', 'Neocaledônio', 687, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Nova Zelândia', 'NZL', 'Neozelandês', 64, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Omã', 'OMN', 'Omani', 968, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Palau', 'PLW', 'Palauense', 680, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Panamá', 'PAN', 'Panamenho', 507, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Papua-Nova Guiné', 'PNG', 'Papuásio', 675, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Paquistão', 'PAK', 'Paquistanês', 92, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Paraguai', 'PRY', 'Paraguaia', 595, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Peru', 'PER', 'Peruana', 51, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Polinésia Francesa', 'PYF', 'Polinésio', 689, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Polônia', 'POL', 'Polonesa', 48, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Porto Rico', 'PRI', 'Portorriquenha', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Portugal', 'PRT', 'Portuguesa', 351, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Qatar', 'QAT', '', 974, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Quirguistão', 'KGZ', 'Quirguiz', 996, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('República Centro-Africana', 'CAF', 'Centro-africano', 236, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('República Dominicana', 'DOM', 'Dominicano', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('República Tcheca', 'CZE', 'Checo', 420, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Romênia', 'ROM', 'Romena', 40, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ruanda', 'RWA', 'Ruandês', 250, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Saara Ocidental', 'ESH', 'Saráui', 212, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('São Vicente e Granadinas', 'VCT', 'São-vicentino', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Samoa Ocidental', 'ASM', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('San Marino', 'SMR', 'Samarinês', 378, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Santa Helena', 'SHN', 'Santa-helenense', 290, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Santa Lúcia', 'LCA', 'Santalucense', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('São Cristóvão e Névis', 'KNA', 'São-cristovense', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('São Tomé e Príncipe', 'STP', 'São-tomense', 239, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Senegal', 'SEN', 'Senegalês', 221, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Serra Leoa', 'SLE', 'Leonês', 232, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Síria', 'SYR', 'Sírio', 963, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Somália', 'SOM', 'Somali', 252, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Sri Lanka', 'LKA', 'Cingalês', 94, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('St. Pierre and Miquelon', 'SPM', 'Pedro-miquelonense', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Suazilândia', 'SWZ', 'Suazi', 268, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Sudão', 'SDN', 'Sudanês', 249, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Suécia', 'SWE', 'Sueca', 46, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Suíça', 'CHE', 'Suíça', 41, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Suriname', 'SUR', 'Surinamês', 597, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Tadjiquistão', 'TJK', 'Tadjique', 992, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Tailândia', 'THA', 'Tailândesa', 66, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Taiwan', 'TWN', 'Taiwanês', 886, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Tanzânia', 'TZA', 'Tanzaniano', 255, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Território Britânico do Oceano índico', 'IOT', '', 246, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Territórios do Sul da França', 'ATF', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Timor Leste', 'TMP', 'Timorense', 670, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Togo', 'TGO', 'Togolês', 228, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Tonga', 'TON', 'Tonganês', 676, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Trinidad e Tobago', 'TTO', 'Trinitino ou Tobaguiano', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Tunísia', 'TUN', 'Tunisiano', 216, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Turcomenistão', 'TKM', 'TurcomanoTuvalu Tuvaluano', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Turquia', 'TUR', 'Turco', 90, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Tuvalu', 'TUV', 'Tuvaluano', 688, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ucrânia', 'UKR', 'Ucraniana', 380, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Uganda', 'UGA', 'Ugandense', 256, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Uruguai', 'URY', 'Uruguaia', 598, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Uzbequistão', 'UZB', 'Uzbeque', 998, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Vanuatu', 'VUT', 'Vanuatense', 678, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Vaticano', 'VAT', 'Vaticano', 379, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Venezuela', 'VEN', 'Venezuelana', 58, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Vietnã', 'VNM', 'Vietnamita', 84, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Zaire', 'ZAR', 'Zairense', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Zâmbia', 'ZMB', 'Zambiano', 260, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Zimbábue', 'ZWE', 'Zimbabuano', 263, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Brasil', 'BRA', 'Brasileira', 55, '1');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('África do Sul', 'ZAF', 'Sul-africano', 27, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Albânia', 'ALB', 'Albanês', 355, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Alemanha', 'DEU', 'Alemã', 49, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Argélia', 'DZA', 'Argelino', 213, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Andorra', 'AND', 'Andorrano', 376, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Angola', 'AGO', 'Angolana', 244, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Anguilla', 'AIA', 'Anguilano', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Antártida', 'ATA', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Antígua e Barbuda', 'ATG', 'Antiguano', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Antilhas Holandesas', 'ANT', 'Antilhano', 599, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Arábia Saudita', 'SAU', 'Saudita', 966, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Argentina', 'ARG', 'Argentina', 54, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Armênia', 'ARM', 'Armênio', 374, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Aruba', 'ABW', 'Arubano', 297, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Austrália', 'AUS', 'Australiana', 61, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Áustria', 'AUT', 'Austriaca', 43, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Azerbaijão', 'AZE', 'Azerbaijano', 994, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Bahamas', 'BHS', 'Bahamense', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Bahrein', 'BHR', 'Bareinita', 973, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Bangladesh', 'BGD', 'Bengalês', 880, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Barbados', 'BRB', 'Barbadiano', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Belarus', 'BLR', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Bélgica', 'BEL', 'Belga', 32, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Belize', 'BLZ', 'Belizenho', 501, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Benin', 'BEN', 'Beninense', 229, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Bermudas', 'BMU', 'Bermudenho', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Bolívia', 'BOL', 'Boliviana', 591, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Bósnia-Herzegóvina', 'BIH', 'Bósnio', 387, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Botsuana', 'BWA', 'Betchuano', 267, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Afeganistão', 'AFG', 'Afegane', 93, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Brunei', 'BRN', 'Bruneiano', 673, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Bulgária', 'BGR', 'Búlgaro', 359, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Burkina Fasso', 'BFA', 'Burquinense', 226, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Burundi', 'BDI', 'Burundiense', 257, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Butão', 'BTN', 'Butanês', 975, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Cabo Verde', 'CPV', 'Cabo-verdiano', 238, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Camarões', 'CMR', 'Camaronês', 237, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Camboja', 'KHM', 'Cambojano', 855, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Canadá', 'CAN', 'Canadense', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Cazaquistão', 'KAZ', 'Cazaque', 7, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Chade', 'TCD', 'Chadiense', 235, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Chile', 'CHL', 'Chilena', 56, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('China', 'CHN', 'Chinesa', 86, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Chipre', 'CYP', 'Cipriota', 357, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Cingapura', 'SGP', 'Cingapuriano', 65, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Colômbia', 'COL', 'Colombiana', 57, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Congo', 'COG', 'Congolês', 242, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Coréia do Norte', 'PRK', 'Norte-coreano', 850, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Coréia do Sul', 'KOR', 'Sul-coreano', 82, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Costa do Marfim', 'CIV', 'Marfinense', 225, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Costa Rica', 'CRI', 'Costa-riquenho', 506, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Croácia (Hrvatska)', 'HRV', 'Croata', 385, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Cuba', 'CUB', 'Cubana', 53, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Dinamarca', 'DNK', 'Dinamarquesa', 45, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Djibuti', 'DJI', 'Djibutiense', 253, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Dominica', 'DMA', 'Dominiquês', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Egito', 'EGY', 'Egipcia', 20, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('El Salvador', 'SLV', 'Salvadorenho', 503, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Emirados Árabes Unidos', 'ARE', 'Árabe', 971, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Equador', 'ECU', 'Equatoriana', 593, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Eritréia', 'ERI', 'Eritréio', 291, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Eslováquia', 'SVK', 'Eslovaco', 421, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Eslovênia', 'SVN', 'Esloveno', 386, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Espanha', 'ESP', 'Espanhola', 34, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Estados Unidos', 'USA', 'Americana', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Estônia', 'EST', 'Estoniano', 372, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Etiópia', 'ETH', 'Etíope', 251, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Federação Russa', 'RUS', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Fiji', 'FJI', 'Fijiano', 679, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Filipinas', 'PHL', 'Filipina', 63, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Finlândia', 'FIN', 'Finlandesa', 358, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('França', 'FRA', 'Francesa', 33, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('França Metropolitana', 'FXX', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Gabão', 'GAB', 'Gabonense', 241, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Gâmbia', 'GMB', 'Gambiano', 220, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Gana', 'GHA', 'Ganense', 233, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Geórgia', 'GEO', 'Georgiano', 995, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Gibraltar', 'GIB', 'Gibraltino', 350, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Grã-Bretanha (Reino Unido, UK)', 'GBR', '', 44, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Granada', 'GRD', 'Granadino', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Grécia', 'GRC', 'Grega', 30, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Groenlândia', 'GRL', 'Groenlandês', 299, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Guadalupe', 'GLP', 'Guadalupano', 590, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Guam (Território dos Estados Unidos)', 'GUM', 'Guamês', 671, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Guatemala', 'GTM', 'Guatemalteca', 502, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Guiana', 'GUY', 'Guianense', 592, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Guiana Francesa', 'GUF', 'Guianense', 594, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Guiné', 'GIN', 'Guineano', 224, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Guiné Equatorial', 'GNQ', 'Guinéu-equatoriano', 240, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Guiné-Bissau', 'GNB', 'Guineense', 245, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Haiti', 'HTI', 'Haitiano', 509, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Holanda', 'NLD', 'Holandesa', 31, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Honduras', 'HND', 'Hondurenho', 504, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Hong Kong', 'HKG', '', 852, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Hungria', 'HUN', 'Hungara', 36, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Iêmen', 'YEM', 'Iemenita', 967, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilha Bouvet (Território da Noruega)', 'BVT', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilha Natal', 'CXR', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilha Pitcairn', 'PCN', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilha Reunião', 'REU', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Cayman', 'CYM', 'Caimanês', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Cocos', 'CCK', 'Coquense', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Comores', 'COM', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Cook', 'COK', 'Cookense', 682, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Faeroes', 'FRO', 'Faroense', 298, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Falkland (Malvinas)', 'FLK', 'Malvinense', 500, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Geórgia do Sul e Sandwich do Sul', 'SGS', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Heard e McDonald (Território da Austrália)', 'HMD', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Marianas do Norte', 'MNP', '', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Marshall', 'MHL', 'Marshallino', 692, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Menores dos Estados Unidos', 'UMI', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Norfolk', 'NFK', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Seychelles', 'SYC', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Salomão', 'SLB', 'Salomônico', 677, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Svalbard e Jan Mayen', 'SJM', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Tokelau', 'TKL', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Turks e Caicos', 'TCA', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Virgens (Estados Unidos)', 'VIR', 'Virginense', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Virgens (Inglaterra)', 'VGB', 'Virginense', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Ilhas Wallis e Futuna', 'WLF', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Índia', 'IND', 'Indiana', 91, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Indonésia', 'IDN', 'Indonésio', 62, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Irã', 'IRN', 'Iraniana', 98, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Iraque', 'IRQ', 'Iraquiana', 964, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Irlanda', 'IRL', 'Irlandesa', 353, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Islândia', 'ISL', 'Islandês', 354, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Israel', 'ISR', 'Israelense', 972, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Itália', 'ITA', 'Italiana', 39, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Iugoslávia', 'YUG', '', null, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Jamaica', 'JAM', 'Jamaicana', 1, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Japão', 'JPN', 'Japonesa', 81, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Jordânia', 'JOR', 'Jordaniana', 962, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Quênia', 'KEN', 'Queniana', 254, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Kiribati', 'KIR', 'Kiribatiano', 686, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Kuwait', 'KWT', 'Kuwaitiano', 965, '0');
insert into localidade_schema.pais (nome, sigla, nacionalidade, codigo_discagem, situacao) values ('Laos', 'LAO', 'Laosiano', 856, '0');